#+Title: Deployable Pinguino Firmware Uploader

* Background

I sometimes give people hardware built around Microchip PICs running
the [[http://pinguino.cc][Pinguino]] bootloader, which makes flashing new firmware as easy as
connecting a usb cable and running a script to handle the usb bulk
transfers.

Although the Pinguino project provides a lot of code, I do not
actually use its IDE to develop: rather, I write directly for XC8,
sometimes using pinguino libraries, sometimes not.  So long as one
sets the offset properly the bootloader doesn’t care.  This way I can
use a proper editor, etc.  In order to install I have a very basic
script which connects to an attached Pinguino device in bootloader
mode.  It is nothing more than a bunch of hacks on top of the uploader
code used by Pinguino itself at the time, and I have made no attempts
to translate Pingunio’s rather idiosyncratic Python (passing lists of
string around to signify status, anyone? and
~VERY_LONG_CONSTANT_NAMES~? ;) ) into something more Pythonic.

Having shipped a project with an embarassing bug in it to the other
side of the Atlantic I needed a basic GUI I could send which would run
first time under Windows.  This turned out to be a complete nightmare,
as the Windoze (Almost)Operating System is headstrong and incompetent
in equal measure, but this repository contains a single installer
which will install a simple program, along with drivers, to do the
upload.

* Installation

Write later.

* Implementation

The Pinguino NSIS installer script was heavily hacked to produce a
NSIS script which compiles to an installer to:

- download and install libusb and the pinguino drivers for windows
- download and install pyinstaller packaged firmware uploader
- add a shortcut.

* Permissions

I have no permission to call this Pinguino-x and will stop doing so if
anybody is offended.  However I hope, rather, that it might stimulate
some interest in this very useful project, which has been rather
unfortunately sidelined by the success of Arduino.
