#+title: Manual Upload Script for Pinguino boards

* Description

This repositories contains a minimal pinguino upload script for those
who at one time used the [[http://pinguino.cc][Pinguino]] ide and now just want to upload code
to PICs flashed with the pinguino bootloader, without needing to load
the whole hog.

It started life as a script I found in the pinguino sources itself,
but which since seems to have been deleted.  It underwent minor
modifications to work with python3, whose usb support is clearly
slightly different from that which was in place back when it was first
written.

I have used it with Pic18F2550/4550 devices.  With anything else it is
untested.

* [2/3] Todo
- [X] error out in uploader if fails
  - Turns out Pinguino, with its typical rather unpythonic python,
    returns a list of strings one of which will be ‘...successfully
    uploaded’ (at least in English) if upload succeeds.  So we can
    test for that.
- [X] Auto-detect attached pinguino, and tell user to pick which if
  more than one found.
  - Slightly harder than it looked.  Let’s just give up for now.
    (Everything I’ve built uses a 4550 so no real problem in the short
    term.)
- [ ] Nicer gui
